### ISSUE TITLE
Launching kinematic services under a namespace

### ISSUE THREAD

**Issue by RaduCorcodel** [diogoalmeida/robot_kinematic_services#1]
Hi Diogo,
I have ROS network where the robot driver runs under an arbitrary namespace. So parameters such as /robot_description are in fact /a_namespace/robot_description. What would be the easiest way to launch the kinematic services then? I looked over your code and all required parameter names seem to be global. Should I simply make them relative so then maybe I can just roslaunch the kinematic services in a group with the namespace the robot driver has?
Thanks,
Radu

**Comment by diogoalmeida** [comment]
Hi Radu,

Nice to see you're using this repo! I believe that this would have to be changed in the kdl manager class, check [here](https://github.com/diogoalmeida/generic_control_toolbox/blob/19136a4eef2053de7bdc977717582230fe886e00/src/kdl_manager.cpp#L8). 

I believe that the issue here would be in using the right namespace. If you manage to adapt this to be general, I would be very thankful if you could do a pull request on it. 

In any case, best of lucks with your work!

Diogo

**Comment by diogoalmeida** [comment]
I have updated the launch file example has mentioned in this [MR](https://github.com/diogoalmeida/robot_kinematic_services/pull/2).
